insert into timeline (id, name, creation_date, update_date, category) values (1, 'Numérique', '2019-12-12', '2019-12-12', 'CNF');
insert into timeline (id, name, creation_date, update_date, category) values (2, 'Data', '2019-12-12', '2019-12-12', 'Data');

insert into card (id, name, date, image_url, timeline_id, description) values (1, 'Facebook', '2004-02-04', 'https://upload.wikimedia.org/wikipedia/commons/7/7c/Facebook_New_Logo_%282015%29.svg', 1, 'Invention du plus célèbre réseau social');
insert into card (id, name, date, image_url, timeline_id, description) values (2, 'Twitter', '2006-03-21', 'https://upload.wikimedia.org/wikipedia/fr/c/c8/Twitter_Bird.svg', 1, 'Le réseau social préféré de D. Trump');
insert into card (id, name, date, image_url, timeline_id, description) values (3, 'Snapchat', '2011-09-01', 'https://upload.wikimedia.org/wikipedia/fr/a/ad/Logo-Snapchat.png', 1, 'Pour ceux qui ont peur que les photos restent ...');
insert into card (id, name, date, image_url, timeline_id, description) values (4, 'Windows', '1985-11-20', 'https://upload.wikimedia.org/wikipedia/commons/d/df/Microsoft_Windows_1.0_screenshot.png', 1, 'Le premier OS de Microsoft');
insert into card (id, name, date, image_url, timeline_id, description) values (5, 'Web', '1989-03-13', 'https://upload.wikimedia.org/wikipedia/commons/b/b2/WWW_logo_by_Robert_Cailliau.svg', 1, 'L''invention de Tim Berners Lee');
insert into card (id, name, date, image_url, timeline_id, description) values (6, 'Amazon', '1994-07-05', 'https://upload.wikimedia.org/wikipedia/commons/a/a9/Amazon_logo.svg', 1, 'Le commerce en ligne');
insert into card (id, name, date, image_url, timeline_id, description) values (7, 'Apple', '1976-04-01', 'https://upload.wikimedia.org/wikipedia/commons/f/fa/Apple_logo_black.svg', 1, 'La marque de Steve !');
insert into card (id, name, date, image_url, timeline_id, description) values (8, 'Google', '1998-09-04', 'https://upload.wikimedia.org/wikipedia/commons/2/2f/Google_2015_logo.svg', 1, 'Le moteur de recherche le plus utilisé en Europe');